config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'tasks#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users, only:[:new, :create, :show]
  resources :sessions, only:[:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  validates :name, presence: true

  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels, source: :task
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels, source: :label

  enum priority: { 低: 0, 中: 1, 高: 2 }

  ## タスク検索機能
  # タスク名検索
  scope :search_name, -> (params) do
    where("name LIKE?", "%#{params}%") if params.present?
  end

  # ステータス検索
  scope :search_status, -> (params) do
    where(status: params) if params.present?
  end

  # ラベル検索
  scope :search_label, -> (params) do
    joins(:labels).where(labels: {id: params}) if params.present?
  end

  # タスク名、ステータス、ラベル検索を統合
  scope :search_tasks, -> (params) do
    if params[:search].present?
      search_name(params[:name])
      .search_status(params[:status])
      .search_label(params[:label_id])
    end
  end

  ## タスクソート機能
  class << self
    def sort_tasks(params)
      return self.order(created_at: 'DESC') if params[:sort].nil?
      if (params[:sort_expired])
        return self.order(:due_date)
      elsif (params[:sort_expired_priority])
        return self.order(priority: 'DESC')
      else
        return self.order(created_at: 'DESC')
      end
    end
  end

  def status_key
    [['未着手', '未着手'], ['着手中', '着手中'], ['完了', '完了']]
  end
end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_destroy :check_disappear_admin
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum:6 }
  has_many :tasks, dependent: :destroy

  private

  def check_disappear_admin
    if self.admin? && User.where(admin: true).count == 1
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create,]
  before_action :check_admin

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザーを新規登録しました！"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.includes(:tasks).all.order('id')
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "「#{@user.name}」さんの情報を更新しました！"
    else
      render :edit_admin_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, alert: "「#{@user.name}」さんの情報を削除しました！"
    else
      redirect_to admin_users_path, alert: "管理者がいなくなるため、削除出来ません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def check_admin
    unless current_user.admin?
      raise Forbidden
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  class Forbidden < ActionController::ActionControllerError
  end

  rescue_from Forbidden, with: :rescue403

  private

  def login_required
    redirect_to new_session_path unless current_user
  end

  def rescue403(e)
    @exception = e
    render 'errors/forbidden', status: 403
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
  end

  def create
    user = User.find_by(email: session_params[:email].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice: "ログインに成功しました！"
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only:[:show, :edit, :update, :destroy]
  PER = 5

  def index
    @tasks = current_user.tasks
    @sorted_tasks = @tasks.sort_tasks(params)
    @searched_tasks = @sorted_tasks.search_tasks(params)
    @finally_tasks = @searched_tasks.page(params[:page]).per(PER)
    @task = Task.new
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "タスク「#{@task.name}」を登録しました！"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスク「#{@task.name}」を更新しました！"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "タスク「#{@task.name}」を削除しました！"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :due_date, :status, :priority, label_ids: [])
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create,]

  def new
    redirect_to user_path(current_user.id), alert: 'ログイン中のユーザー登録は出来ません。' if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id), alert: '覗き見はだめよ❤️' if @user != current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<% if @user.errors.present? %>
  <div class="container alert alert-danger my-3">
    <ul id="error_explanation">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container my-5">
  <h1>ユーザー情報変更(管理者権限)</h1>
  <%= form_with(model: @user, url: admin_user_path, method: :patch, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="form-check my-5">
      <%= f.label :admin, class: 'form-check-label' do %>
        <%= f.check_box :admin, class: 'form-check-iuput' %>管理者権限
      <% end %>
    </div>

    <%= f.submit "#{t('users.update_account')}", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container my-5">
  <h2 class="my-3">登録ユーザー一覧</h2>
  <%= link_to 'ユーザー登録', new_admin_user_path, class: 'btn btn-primary my-3' %>
  <table class="table table-hover table-striped">
    <tr>
      <th>ユーザーID</th>
      <th>ユーザー名</th>
      <th>タスク件数</th>
      <th colspan="2">管理者権限</th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.tasks.size %>件</td>
        <td><%= user.admin? ?  'あり' : 'なし' %></td>
        <td class="user_task"><%= link_to '詳細', admin_user_path(user) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/users/new.html.erb
<% if @user.errors.present? %>
  <div class="container alert alert-danger my-3">
    <ul id="error_explanation">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container my-5">
  <h1>ユーザー登録(管理者権限)</h1>
  <%= form_with(model: @user, url: admin_users_path, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-check my-5">
    <%= f.label :admin, class: 'form-check-label' do %>
      <%= f.check_box :admin, class: 'form-check-iuput' %>管理者権限
    <% end %>
  </div>

    <%= f.submit "#{t('users.create_account')}", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h1 class="my-5">ユーザ情報</h1>
  <table class="table table-hover my-3">
    <tbody>
      <tr>
        <th>ユーザーID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>ユーザー名</th>
        <td><%= @user.name %></td>
      </tr>

      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>

      <tr>
        <th>管理者権限</th>
        <td><%= @user.admin? ? 'あり' : 'なし' %></td>
      </tr>
    </tbody>
  </table>

  <h3 class='mt-5 mb-3'>登録タスク一覧</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t('tasks.name') %></th>
        <th><%= t('tasks.due_date')%></th>
        <th><%= t('tasks.status')%></th>
        <th><%= t('tasks.priority')%></th>
        <th colspan="3"><%= t('tasks.created_at')%></th>
      </tr>
    </thead>
    <% @user.tasks.each do |task| %>
    <tbody>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.due_date %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.created_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'ユーザー編集', edit_admin_user_path(@user), class: "btn btn-outline-success" %>
  <%= link_to 'ユーザー削除', admin_user_path(@user), class: 'btn btn-outline-danger', method: :delete, data: { confirm: "#{@user.name}を削除してよろしいですか？"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm sticky-top navbar-light p-4 border-bottom" id="navi-bar">
      <div class="container-fluid">
          <a class="nav-barbrand" style="color:black;"><span>Taskmate</span></a>
        <div class="collapse navbar-collapse justify-content-end">
          <ul class="navbar-nav">
            <% if current_user %>
              <% if current_user.admin? %>
                <li class="nav-item"><%= link_to '管理者画面', admin_users_path, class: 'nav-link' %></li>
              <% end %>
              <li class="nav-item"><%= link_to 'タスク一覧', tasks_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'ログアウト', session_path(current_user.id), method: :delete, class: 'nav-link' %></li>
            <% else %>
              <li class="nav-item"><%= link_to 'ログイン', new_session_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if flash.notice.present? %>
      <div class="container alert alert-success my-2">
        <%= notice %>
      </div>
    <% elsif flash.alert.present? %>
      <div class="container alert alert-danger my-2">
        <%= alert %>
      </div>
    <% end %>

    <% if logged_in? %>
    <% else %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <%= form_with(model: task, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter task name" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows:5, class: 'form-control', placeholder: "Enter task description" %>
    </div>
    <div class="form-group">
      <%= f.label :due_date %>
      <%= f.text_field :due_date, class: 'form-control', placeholder: "Please enter like => 2020-06-07" %>
    </div>
    <div class="form-group">
      <%= f.label :status %>
      <%= f.select :status, task.status_key, {include_blank: true}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :priority %>
      <%= f.select :priority, Task.priorities.keys, {include_blank: true}, selected: Task.priorities[@task.priority], class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :labels %><br>
      <%= collection_check_boxes(:task, :label_ids, Label.all, :id, :name, include_hidden: false ) do |t|  %>
        <%= t.label { t.check_box + t.text } %>
      <% end %>
    </div>

    <div class="my-5">
      <%= f.submit nil, class: 'btn btn-outline-primary' %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="container my-5">
  <h1><%= t('.edit_task')%></h1>
</div>

<%= render partial: 'form', locals: { task: @task } %>

<div class="container">
  <%= link_to '一覧へ', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="my-3"><%= t('.task_index')%></h1>
  <%= link_to t('.create_task'), new_task_path, class: 'btn btn-outline-primary mr-3' %>
  <%= link_to t('.sort_task'), tasks_path({sort: "true", sort_expired: "true"}), class: 'btn btn-outline-secondary mr-3' %>
  <%= link_to t('.sort_task_priority'), tasks_path({sort: "true", sort_expired_priority: "true"}), class: 'btn btn-outline-secondary mr-3' %>
  <%= link_to t('.all_task'), tasks_path, class: 'btn btn-outline-secondary' %>
</div>

<div class="container my-5 form-group">
  <div class="card shadow px-5 py-3">
  <%= form_with(url: tasks_path, method: :get, local: true) do |f| %>
    <div>
      <%= f.label :name_search, t('.name_search') %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div>
      <%= f.label :status_search, t('.status_search') %>
      <%= f.select :status, @task.status_key, {include_blank: true}, class: 'form-control' %>
    </div>

    <div>
      <%= f.label :label_search, t('.label_search') %>
      <%= f.select :label_id, Label.all.pluck(:name, :id), {include_blank: true}, class: 'form-control' %>
    </div>

    <%= f.hidden_field :search, value: 'true' %>

    <div class="my-3">
      <%= f.submit '検索', class: 'btn btn-outline-primary' %>
    </div>
  <% end %>
  </div>
</div>

<div class="container my-5">
  <table class="table table-hover table-striped">
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('tasks.due_date')%></th>
      <th><%= t('tasks.status')%></th>
      <th><%= t('.priority')%></th>
      <th colspan="3"><%= t('.created_at')%></th>
    </tr>

    <% @finally_tasks.each do |task| %>
      <tr>
        <td><%= link_to task.name, task_path(task) %></td>
        <td><%= task.due_date %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.created_at %></td>
        <td><%= link_to t('tasks.to_edit'), edit_task_path(task), class: "btn btn-outline-success" %></td>
        <td><%= link_to t('tasks.to_delete'),
                        task_path(task),
                        class: 'btn btn-outline-danger',
                        method: :delete,
                        data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}
            %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate @finally_tasks %>
</div>

app/views/tasks/new.html.erb
<div class="container my-5">
  <h1><%= t('.create_new_task')%></h1>
</div>

<%= render partial: 'form', locals: { task: @task } %>

<div class="container">
  <%= link_to t('tasks.to_index'), tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="my-5">タスクの詳細</h1>
  <table class="table table-hover">
    <tbody>
      <tr>
        <th>名称</th>
        <td><%= @task.name %></td>
      </tr>

      <tr>
        <th>詳細</th>
        <td><%= @task.description %></td>
      </tr>

      <tr>
        <th><%= t('tasks.due_date')%></th>
        <td><%= @task.due_date %></td>
      </tr>

      <tr>
        <th><%= t('tasks.status')%></th>
        <td><%= @task.status %></td>
      </tr>

      <tr>
        <th><%= t('tasks.priority')%></th>
        <td><%= @task.priority %></td>
      </tr>

      <tr>
        <th>登録日時</th>
        <td><%= @task.created_at%></td>
      </tr>

      <tr>
        <th>ラベル</th>
        <% @task.labels.each do |l| %>
          <td><%= l.name %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
<div class="container my-4">
  <%= link_to '編集', edit_task_path(@task), class: 'btn btn-outline-success mr-3' %>
  <%= link_to '削除', task_path(@task), method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？"}, class: 'btn btn-outline-danger' %>
</div>
<div class="container">
  <%= link_to '一覧へ', tasks_path %>
</div>

app/views/users/new.html.erb
<% if @user.errors.present? %>
  <div class="container alert alert-danger my-3">
    <ul id="error_explanation">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container my-5">
  <h1>ユーザー登録</h1>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "#{t('users.create_account')}" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="my-5">マイページ</h1>
  <table class="table table-hover">
    <tbody>
      <tr>
        <th>ユーザー名</th>
        <td><%= @user.name %></td>
      </tr>

      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
    </tbody>
  </table>
</div>